FROM {{ docker_hub_username }}/ubuntu-java8:{{ image_tag }}

# Place conf and scripts
ADD ./docker/generated/conf/ {{ common_conf_dir }}

# Mounting point for external configs and scripts
VOLUME ["{{ common_conf_dir }}"]
